meta_product_name: "Diggerz"
meta_title: "Diggerz - Troquer vos vinyles"
meta_description: "Echangez les vinyles dont vous ne voulez plus avec ceux des diggerz autour de vous "
meta_image: "digerz-meta-data.jpg"
twitter_account: "@DiggerzApp"
