:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - default
  - mailers
  - reminders
  - active_storage_analysis
  - active_storage_purge
:schedule:
  schedule_in_progress_reminders:
    cron: '0 0 1 * * *' # Every day at 1:00 UTC
    # cron: '* * * * *' # For tests, runs every minute
    class: Deals::InProgress::ScheduleRemindersJob
